[package]
name = "neur"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
lightningcss = "1.0.0-alpha.68"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
