[package]
name = "neur"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
lightningcss = "1.0.0-alpha.68"
minify-html = "0.18.1"
serde = { version = "1.0", features = ["derive"] }
tera = "1.20.1"
toml = "0.9"
